//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakturisanje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Field
    {
        public int FieldId { get; set; }
        public string FieldName { get; set; }
        public string DocumentId { get; set; }
        public double Price { get; set; }
        public int Amount { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
