//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakturisanje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Fields = new HashSet<Field>();
        }

        [Required(ErrorMessage = "Polje je obavezno")]
        [MaxLength(10, ErrorMessage = "Maksimum je 10 karaktera")]
        public string DocumentId { get; set; }

        [Required(ErrorMessage = "Polje je obavezno")]
        [MaxLength(10, ErrorMessage = "Maksimum je 10 karaktera")]
        public string InvoiceId { get; set; }

        [Required(ErrorMessage = "Polje je obavezno")]
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<double> Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Field> Fields { get; set; }
    }
}
